export type StudentPayload = {
  first_name: string;
  last_name: string;
  email: string;
  name?: string;
  phone?: string;
  country?: string;
  status?: string;
  password?: string;
  primary_goal?: string;
  platform_institution_id?: number | null;
  institution_name?: string | null;
  selected_courses?: string[];
  applications?: number;
  avatar?: string;
  middle_name?: string;
  dob?: string;
  nationality?: string;
  passport_number?: string;
  passport_expiry?: string;
  gender?: string;
  referral_source?: string;
  recruitment_partner?: string;
  recruitment_type?: string;
  education?: string;
  country_of_interest?: string[];
  services_of_interest?: string[];
  services_other_text?: string;
  application_stats?: Record<string, any>;
};
